-- MySQL Script generated by MySQL Workbench
-- Thu Aug 22 14:47:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `chaelyn` DEFAULT CHARACTER SET utf8 ;
USE `chaelyn` ;

-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
drop table book;
drop table author;
CREATE TABLE IF NOT EXISTS `chaelyn`.`author` (
  `authorno` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `phone` VARCHAR(30) NULL,
  PRIMARY KEY (`authorno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chaelyn`.`book` (
  `isbn` VARCHAR(50) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `publisher` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `description` VARCHAR(200) NULL,
  `authorno` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_book_author_idx` (`authorno` ASC) VISIBLE,
  CONSTRAINT `fk_book_author`
    FOREIGN KEY (`authorno`)
    REFERENCES `chaelyn`.`author` (`authorno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------------
use chaelyn;
show tables;
desc book;
desc author;

insert into author(authorno, name, phone)
values(8001, '류치현', '010-1234-1234'),
(8002, '손경수', '010-1234-1235'),
(8003, '김정원', '010-1235-1234'),
(8004, '김아현', '010-1234-1236'),
(8005, '김희주', '010-1234-1238');

commit;
select * from author;
select count(*) from author;

insert into book(isbn, title, publisher, price, description, authorno)
values('80001','모던 아현을 위한 책','불국사',2000, '자바를 사랑하는 분께', 8001), 
('80002','모던 보이를 위한 책','아현사',3000, '떡볶기를 사랑하는 분께', 8002),
('80003','누구를 위하여 예비군에 가는가','치킨사',4000, '알골향상을 위한 분께', 8003),
('80004','치킨을 아는가', '도사', 4000, '닭을 잘 튀기는 법', 8004),
('80005','사과를 아는가','국사',3000, '사과를 잘 고르는 법', 8005);

select * from book;

select count(*), authorno from book group by authorno;

select a.name, a.phone, b.title, b.publisher from author a, book b
where a.authorno = b.authorno;

select b.title, b.price, a.name from book b, author a
where a.authorno=b.authorno;

select b.title, b.isbn, b.publisher from book b, author a
where a.authorno=b.authorno and a.name='류치현';

--
select sum(price), publisher from book group by publisher;

--
select b.title, b.publisher, b.price, a.name from book b, author a group by a.name;

-- outer join
select b.title, b.publisher, b.price, a.name
from book b right join author a
on b.authorno=a.authorno;


select b.title title, b.publisher publisher, sum(b.price) price, a.name name
from book b, author a
where b.authorno=a.authorno
group by a.name;














